"""The source registry: one machine-readable record of every source, with its state.

    config/sources.yaml       declarations, maintained by hand: what a source is, how often it publishes, when it is stale, its terms
    operations/sources.yaml   GENERATED here from the declarations, the run logs and the clock. Never edited.

Nothing about the state of a source is typed anywhere: last attempt, last success, newest data, status and error are read
from the append-only run records of the layer that fetches it. The same records with a later clock give a staler answer.
This module knows no source by name; it reads what the declarations point to, so a layer is added by declaring it.

    python -m src.observability.registry            # write the registry and print the table
    python -m src.observability.registry --check    # exit 1 if the declarations are inconsistent

Status of a source
    DISABLED        declared inactive
    RESEARCH_ONLY   declared as research: held for study, fetched by no pipeline
    FAILED          no successful run on record, or the newest attempt failed and the last success is older than the limit
    DEGRADED        the newest attempt failed, was partial or was rate limited, and the data held are still within the limit
    STALE           no check within stale_after_days, or the newest data are older than data_stale_after_days
    HEALTHY         otherwise"""
import datetime, os, sys
import yaml
from src.observability import records, sources

DECLARED = os.path.join(sources.ROOT, "config", "sources.yaml")
REGISTRY = os.path.join(sources.OPS_DIR, "sources.yaml")
STATUSES = ("HEALTHY", "STALE", "DEGRADED", "FAILED", "DISABLED", "RESEARCH_ONLY")
REQUIRED = ("id", "name", "url", "type", "frequency", "active", "license", "coverage", "notes")
SCHEDULED = ("schedule",)
HEADER = ("# GENERATED by src/observability/registry.py from config/sources.yaml, the run logs and the clock. Do not edit:\n"
          "# the next run overwrites it. To change what a source is, edit config/sources.yaml; its state cannot be set by hand.\n")


def now_utc():
    return datetime.datetime.now(datetime.timezone.utc)


def parse_time(s):
    """A time of a run record or of an observation as UTC. Accepts a timestamp with Z or an offset, a day, or a month
    (read as its last day). None when it cannot be read."""
    if not s or not isinstance(s, str): return None
    s = s.strip()
    try:
        if len(s) == 7:
            y, m = int(s[:4]), int(s[5:7]); nxt = datetime.datetime(y + (m == 12), m % 12 + 1, 1, tzinfo=datetime.timezone.utc)
            return nxt - datetime.timedelta(seconds=1)
        if len(s) == 10: return datetime.datetime.strptime(s, "%Y-%m-%d").replace(tzinfo=datetime.timezone.utc)
        t = datetime.datetime.fromisoformat(s.replace("Z", "+00:00"))
        return (t if t.tzinfo else t.replace(tzinfo=datetime.timezone.utc)).astimezone(datetime.timezone.utc)
    except (ValueError, TypeError): return None


def declared(path=None):
    with open(path or DECLARED, encoding="utf-8") as f: doc = yaml.safe_load(f)
    return doc.get("layers", {}), doc.get("sources", [])


def check_declarations(path=None):
    """Problems of the declarations: a missing field, a repeated id, an unknown layer, or a pipeline source whose address or
    interval differs from the pipeline's own table (the two must never drift apart)."""
    layers, decl = declared(path); problems = []; ids = [d.get("id") for d in decl]
    for i in sorted({x for x in ids if ids.count(x) > 1}, key=str): problems.append(f"{i}: declared more than once")
    for d in decl:
        for k in REQUIRED:
            if k not in d: problems.append(f"{d.get('id')}: field {k} missing")
        if d.get("layer") and d["layer"] not in layers: problems.append(f"{d.get('id')}: layer {d['layer']} is not declared")
        if d.get("layer") and d.get("active") and d.get("type") != "research" and "stale_after_days" not in d: problems.append(f"{d.get('id')}: a fetched source needs stale_after_days")
    by = {d.get("id"): d for d in decl}
    for sid, cfg in sources.SOURCES.items():
        d = by.get(sid)
        if d is None: problems.append(f"{sid}: fetched by the pipeline and not declared"); continue
        if d.get("layer") != "core": problems.append(f"{sid}: must be declared in layer core")
        if d.get("url") != cfg["url"]: problems.append(f"{sid}: declared address differs from the pipeline's")
        if d.get("name") != cfg["name"]: problems.append(f"{sid}: declared name differs from the pipeline's")
        if float(d.get("check_every_days", -1)) != float(cfg["check_days"]) or float(d.get("stale_after_days", -1)) != float(cfg["check_days"] * cfg["grace"]): problems.append(f"{sid}: declared interval or stale limit differs from the pipeline's")
        if bool(d.get("production")) != bool(cfg["production"]): problems.append(f"{sid}: declared production flag differs from the pipeline's")
    for d in decl:
        if d.get("layer") == "core" and d.get("id") not in sources.SOURCES: problems.append(f"{d.get('id')}: declared in layer core and unknown to the pipeline")
    return problems


def _iso(t):
    return None if t is None else t.strftime("%Y-%m-%dT%H:%M:%SZ")


def entry(d, layer, runs, now):
    """The registry record of one declared source. `runs`: the records of its layer's log, in order."""
    out = {"id": d["id"], "name": d["name"], "url": d["url"], "type": d["type"], "frequency": d["frequency"], "active": bool(d["active"]), "license": d["license"],
           "last_success": None, "last_attempt": None, "latest_data": None, "stale_after": None if d.get("stale_after_days") is None else f"{float(d['stale_after_days']):g} days", "status": None, "error": "",
           "coverage": d["coverage"], "notes": d["notes"], "layer": d.get("layer"), "production": bool(d.get("production")), "feeds": list(d.get("feeds") or []),
           "check_every_days": d.get("check_every_days"), "stale_after_days": d.get("stale_after_days"), "data_stale_after_days": d.get("data_stale_after_days"),
           "last_result": None, "last_trigger": None, "scheduled_runs": 0, "manual_runs": 0, "data_mode": None, "record_count": None, "checksum": None, "validation": None}
    if not d["active"]: out.update(status="DISABLED", error=""); return out
    if d["type"] == "research" or not d.get("layer"): out.update(status="RESEARCH_ONLY"); return out
    tk, ok_set, part = layer["time"], set(layer["success"]), set(layer.get("partial") or [])
    mine = [r for r in runs if r.get("source") == d["id"] and r.get(tk)]
    ok = [r for r in mine if r.get("result") in ok_set | part]; last, last_ok = (mine[-1] if mine else None), (ok[-1] if ok else None)   # a partial answer holds data: it counts for the times, never for HEALTHY
    fetched = [r for r in ok if r.get("result") != "SEEDED" and r.get("result") in ok_set]                                     # a seed is a copy of a snapshot, not a fetch
    latest = None
    for r in ok:
        for k in layer["latest"]:
            v = r.get(k)
            if v and (latest is None or str(v) > str(latest)): latest = str(v)
            if v: break
    out.update(last_attempt=last.get(tk) if last else None, last_success=last_ok.get(tk) if last_ok else None, latest_data=latest, last_result=last.get("result") if last else None,
               last_trigger=last.get("trigger") if last else None, scheduled_runs=sum(1 for r in fetched if r.get("trigger") in SCHEDULED),
               manual_runs=sum(1 for r in mine if r.get("trigger") not in SCHEDULED and r.get("result") != "SEEDED"),
               record_count=next((last_ok.get(k) for k in ("record_count", "rows") if last_ok and last_ok.get(k) is not None), None),
               checksum=next((last_ok.get(k) for k in ("checksum", "file_sha256") if last_ok and last_ok.get(k)), None), validation=(last_ok or {}).get("validation") or None)
    limit = float(d["stale_after_days"]); why = (last or {}).get("error") or (last or {}).get("failure_reason") or ""
    t_ok = parse_time(last_ok.get(tk)) if last_ok else None; age = None if t_ok is None else (now - t_ok).total_seconds() / 86400
    last_good = bool(last) and last.get("result") in ok_set
    t_data = parse_time(latest); data_age = None if t_data is None else (now - t_data).total_seconds() / 86400; dl = d.get("data_stale_after_days")
    if not mine: status, err = "FAILED", "no run is recorded for this source"
    elif last_ok is None: status, err = "FAILED", why or f"no successful run on record; the newest attempt gave {last.get('result')}"
    elif not last_good and age > limit: status, err = "FAILED", (why or f"the newest attempt gave {last.get('result')}") + f"; last success {age:.0f} days ago"
    elif not last_good: status, err = "DEGRADED", (why or f"the newest attempt gave {last.get('result')}") + ("; what was answered is held and shown as partial" if last.get("result") in part else "; the data of the last success are held")
    elif age > limit: status, err = "STALE", f"not checked for {age:.0f} days; a check is expected every {float(d['check_every_days']):g} days (limit {limit:g})"
    elif dl is not None and data_age is not None and data_age > float(dl): status, err = "STALE", f"the newest data are {data_age:.0f} days old; the source was reached and has published nothing newer (limit {float(dl):g} days)"
    else: status, err = "HEALTHY", ""
    out.update(status=status, error=err, data_mode="AUTOMATED" if status == "HEALTHY" and fetched and fetched[-1].get("trigger") in SCHEDULED else "SNAPSHOT")
    return out


def build(now=None, declared_path=None, root=None):
    """The registry as a dictionary: every declared source with its state at `now`."""
    now = now or now_utc(); root = root or sources.ROOT; layers, decl = declared(declared_path); logs = {}
    for name, layer in layers.items(): logs[name] = records.read(os.path.join(root, layer["log"].replace("/", os.sep)))
    rows = [entry(d, layers.get(d.get("layer")), logs.get(d.get("layer"), []), now) for d in decl]
    count = {s: sum(1 for r in rows if r["status"] == s) for s in STATUSES}
    prod = [r for r in rows if r["production"]]
    return {"generated_at": _iso(now), "version": 1, "summary": {"sources": len(rows), **count, "production": len(prod), "production_healthy": sum(1 for r in prod if r["status"] == "HEALTHY"),
                                                                  "scheduled_runs": sum(r["scheduled_runs"] for r in rows), "manual_runs": sum(r["manual_runs"] for r in rows)},
            "logs_intact": {name: not records.verify(os.path.join(root, layer["log"].replace("/", os.sep))) for name, layer in layers.items()}, "sources": rows}


def write(reg, path=None):
    path = path or REGISTRY; os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write(HEADER); yaml.safe_dump(reg, f, sort_keys=False, allow_unicode=True, width=1000)
    return path


def read(path=None):
    with open(path or REGISTRY, encoding="utf-8") as f: return yaml.safe_load(f)


def main(argv):
    problems = check_declarations()
    for p in problems: print("DECLARATION PROBLEM:", p)
    if "--check" in argv: return 1 if problems else 0
    reg = build(); write(reg)
    for r in reg["sources"]: print(f"{r['status']:14} {r['id']:30} last success {str(r['last_success'] or '-'):21} newest data {str(r['latest_data'] or '-')[:25]:26} {r['error'][:90]}")
    s = reg["summary"]; print(f"{s['sources']} sources: " + ", ".join(f"{s[k]} {k}" for k in STATUSES if s[k]) + f"; scheduled runs on record {s['scheduled_runs']}, started by hand {s['manual_runs']}")
    return 1 if problems else 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
